const SUPPORTED_LANGUAGES = {
  en: 'English',
  es: 'Spannish',
  fr: 'French',
  it: 'Italian',
  ar: 'Arabic',
  bn: 'Bangla',
  cs: 'Czech',
  da: 'Danish',
  de: 'German',
  el: 'Greek',
  fi: 'Finnish',
  he: 'Hebrew',
  hi: 'Hindi',
  hu: 'Hungarian',
  id: 'Indonesian',
  ja: 'Japanese',
  ko: 'Korean',
  nl: 'Dutch',
  no: 'Norwegian',
  pl: 'Polish',
  pt: 'Portugese',
  ro: 'Romanian',
  ru: 'Russian',
  sk: 'Slovak',
  sv: 'Swedish',
  ta: 'Tamil',
  th: 'Thai',
  tr: 'Turkish',
  zh: 'Chinese'
}

module.exports = SUPPORTED_LANGUAGES
